on:
  schedule:
    - cron: "15 5 1-24 12 *"
  workflow_dispatch:
  

jobs:
  pull_input:
    name: "Pull the day's input"
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Make folder
        run: mkdir -p "$(date +%Y)"/"$(date +%d)"/
      - name: Download input
        run: curl 'https://adventofcode.com/2022/day/"$(date +%-d)"/input' -H Cookie >-
          session=${{ secrets.AOC_SESSION_ID }}
          > "$(date +%Y)"/"$(date +%d)"/input.txt
        
